datasets:
  UTKFace:
    train:
      metadata_file: "../AUFairGAN/data/UTKface_inthewild/UTKface_train_images_location.csv"
      img_dir: "../AUFairGAN/data/UTKface_inthewild/original_images/"
      frac: .10
      batch_size: 8
      img_dim: (224, 224)
      shuffle: True
      num_workers: 4  # Number of subprocesses for data loading
    val:
      metadata_file: "../AUFairGAN/data/UTKface_inthewild/UTKface_validation_images_location.csv"
      img_dir: "../AUFairGAN/data/UTKface_inthewild/original_images/"
      frac: 1.00
      batch_size: 8
      img_dim: (224, 224)
      shuffle: True
      num_workers: 4  # Number of subprocesses for data loading
    test:
      metadata_file: "../AUFairGAN/data/UTKface_inthewild/UTKface_test_images_location.csv"
      img_dir: "../AUFairGAN/data/UTKface_inthewild/original_images/"
      frac: 1.00
      img_dim: (224, 224)
      batch_size: 8
      shuffle: True
      num_workers: 4  # Number of subprocesses for data loading
      groups: ['male', 'female']

  CelebA:
    train:
      metadata_file: "../AUFairGAN/data/celeba/celeba_train.csv"
      img_dir: "../AUFairGAN/data/celeba/img_align_celeba/"
      frac: 1.00
      img_dim: (224, 224)
      batch_size: 8
      shuffle: True
      num_workers: 4  # Number of subprocesses for data loading
    val:
      metadata_file: "../AUFairGAN/data/celeba/celeba_val.csv"
      img_dir: "../AUFairGAN/data/celeba/img_align_celeba/"
      frac: 1.00
      img_dim: (224, 224)
      batch_size: 8
      shuffle: True
      num_workers: 4  # Number of subprocesses for data loading
    test:
      metadata_file: "../AUFairGAN/data/celeba/celeba_test.csv"
      img_dir: "../AUFairGAN/data/celeba/img_align_celeba/"
      frac: 1.00
      img_dim: (64, 64)
      groups: ['male', 'female']
      batch_size: 32
      shuffle: True
      num_workers: 4  # Number of subprocesses for data loading

  MIMIC-III:
    metadata_file: './data/dataset2/labels.csv'
    img_dir: './data/dataset2/images'
    batch_size: 64
