models:
  celeba_cnn:
    model_class: CNNModel
    params:
      num_classes: 2
      learning_rate: 0.001
      num_epochs: 100

  celeba_med_transformer:
    model_class: MedViT
    params:
      num_classes: 2
      learning_rate: 0.001
      num_epochs: 100


  utkface_cnn:
    model_class: CNNModel
    params:
      num_classes: 3
      learning_rate: 0.001
      num_epochs: 100

  utkface_transformer:
    model_class: ViT
    params:
      num_classes: 3
      learning_rate: 0.001
      num_epochs: 100

  
  utkface_med_transformer:
    model_class: MedViT
    params:
      num_classes: 3
      learning_rate: 0.001
      num_epochs: 100

  EUFairGAN:
    model_class: EUFairGAN
    params:
      num_classes: 2
      learning_rate: 0.0001
      num_epochs: 100
      esrgan_disc_learning_rate: 0.0001
      esrgan_gen_learning_rate: 0.0001
      sensitive_disc_learning_rate: 0.0001
      

